name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: >-
            lint
            test

      - name: Run tests
        run: pixi run coverage
